spring:
  application:
    name: waRestaurant

  datasource:
    url: jdbc:postgresql://localhost:5432/waRestaurant
    username: postgres
    password: celina
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 20
      maximum-pool-size: 30
      auto-commit: false


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
